GLOBAL:
  GRAMMAR_METHOD: 'LL1'
  GRAMMAR_TREE_VISUALIZATION: TRUE

GRAMMAR:
  START: 'Program'
  PRODUCTION_ADDRESS: 'assets\SNL_P.txt'
  VT_ADDRESS: 'assets\SNL_VT.txt'
  VN_ADDRESS: 'assets\SNL_VN.txt'
